### ISSUE TITLE
No color in urxvt

### ISSUE THREAD

**Issue by mlmatlock** [doums/milcheck#1]
No colored output in urxvt; xfce4-terminal looks great.

**Comment by doums** [comment]
Hi,

To manage the output color I use the lib [Termion](https://docs.rs/termion/1.5.3/termion/). More precisely I use its [Rgb](https://docs.rs/termion/1.5.3/termion/color/struct.Rgb.html) structure, which creates a truecolor value. The problem is urxvt [does not support](https://gist.github.com/XVilka/8346728#gistcomment-3017349) truecolor. That's why you do not have color with it. But Termion provides some default color. But I do not know if it is truecolor or not. It is difficult for me to solve this problem right now. But I will try !

**Comment by mlmatlock** [comment]
Thanks, doums.

Please don't bang your head over this; I had thought it was related to urxvt's difficulty with colors and piped outputs.

It's not a show-stopper, output is still readable.  Maybe you can put a little note on the readme regarding urxvt.

In the meantime, I'm closing this.  Thanks for this handy little app!

**Comment by doums** [comment]
Hi!

I have good news, I added support for 256 colors and now colors work fine on urxvt (tested myself).
