### ISSUE TITLE
Milcheck failing 

### ISSUE THREAD

**Issue by tim3dman** [doums/milcheck#5]
Hi doums, today when running Milcheck on my Arch Linux system it is timing out with the following error.

error: error decoding response body: operation timed out

I have internet and am able to download updates from the mirror. I changed the mirror with no effect.

**Comment by tim3dman** [comment]
Hey I just restarted and tried again and it worked ok. Hmmm

**Comment by doums** [comment]
Hi!

Based on the error you got, it seems the HTTP fetch of the mirror data timed out, likely because "decoding the response body" took an unusually long time. But I don't know why.

Weird error. And I don't think this is related to the reboot of your machine. Sadly I can't help much.

Anyway, glad to see the problem is gone.
